export interface TermsInfoItem {
  label: string;
  value: string;
  href?: string;
}

export interface TermsParagraphBlock {
  type: 'paragraph';
  text: string;
  uppercase?: boolean;
}

export interface TermsListBlock {
  type: 'list';
  items: string[];
}

export type TermsBlock = TermsParagraphBlock | TermsListBlock;

export interface TermsSection {
  id: string;
  title: string;
  blocks?: TermsBlock[];
  subsections?: TermsSection[];
}

export const termsIntro = [
  `These Terms of Use and Service (“Terms”) together with the Privacy Policy constitute a legally binding Agreement (“Agreement”) between You and Ctruh Technologies Private Limited (“Ctruh,” “Company,” “We,” “Us,” or “Our”), a company incorporated under the Companies Act, 2013 (India), with respect to Your use of Commverse Studio (“Platform” or “Services”), accessible at commverse.studio.`,
  `This document is an electronic record generated by a computer system and does not require any physical or digital signatures. BY ACCESSING OR USING THE PLATFORM IN ANY CAPACITY, YOU SIGNIFY THAT YOU HAVE READ, UNDERSTOOD, AND UNCONDITIONALLY AGREE TO BE BOUND BY THESE TERMS. IF YOU DO NOT AGREE, YOU MUST IMMEDIATELY DISCONTINUE ALL USE.`,
];

export const termsLegalInfo: TermsInfoItem[] = [
  {
    label: 'Legal Entity',
    value: 'Ctruh Technologies Private Limited',
  },
  {
    label: 'Platform',
    value: 'Commverse Studio (commverse.studio)',
  },
  {
    label: 'Incorporated Under',
    value: 'Companies Act, 2013 — India',
  },
  {
    label: 'Registered Address',
    value:
      '3rd floor, Obeya Tranquil, 1185, 5th Main Rd, 7th Sector, HSR Layout, Bengaluru, Karnataka 560102',
  },
  {
    label: 'Contact Email',
    value: 'contact@ctruh.com',
    href: 'mailto:contact@ctruh.com',
  },
  {
    label: 'Legal / Compliance',
    value: 'legal@ctruh.com',
    href: 'mailto:legal@ctruh.com',
  },
];

export const termsSections: TermsSection[] = [
  {
    id: '1',
    title: 'Acceptance of the Agreement',
    blocks: [
      {
        type: 'paragraph',
        text: 'You may enter into and be bound by this Agreement only if:',
      },
      {
        type: 'list',
        items: [
          'You are a natural person of legal age and possess the mental capacity to form a binding contract under Applicable Law, including under the Indian Contract Act, 1872;',
          'You are a juristic person lawfully existing with all necessary authorizations, permits, and authority to enter into and perform this Agreement; and',
          'You are not legally barred or restricted from accessing the Platform or using the Services under any Applicable Law.',
        ],
      },
      {
        type: 'paragraph',
        text: 'We do not want any person to access the Services who does not understand, approve, or accept each and every provision of this Agreement. You are therefore requested to read these Terms and the Privacy Policy carefully before proceeding.',
      },
      {
        type: 'paragraph',
        text: 'You will be deemed to have accepted and agreed to these Terms by any of the following acts:',
      },
      {
        type: 'list',
        items: [
          'Accessing the Platform or any part thereof;',
          'Browsing, navigating, or surfing the Platform;',
          'Creating a Registered Account on the Platform;',
          'Clicking “I Agree,” “Sign Up,” “Get Started,” or any equivalent affirmative action; or',
          'Availing any Service available on the Platform.',
        ],
      },
      {
        type: 'paragraph',
        text: 'If You are entering into this Agreement on behalf of a company or other legal entity, You represent that You have the authority to bind that entity to these Terms. If You do not have such authority, You must not access or use the Services.',
      },
    ],
  },
  {
    id: '2',
    title: 'Definitions and Interpretation',
    blocks: [
      {
        type: 'paragraph',
        text: 'The following capitalized terms shall have the meanings set out below throughout this Agreement:',
      },
      {
        type: 'list',
        items: [
          '“Applicable Law” — Any law, statute, ordinance, regulation, rule, order, judgment, decree, or policy enacted or issued by the Government of India or any competent authority thereof, including the Information Technology Act, 2000, the Digital Personal Data Protection Act, 2023, the Indian Contract Act, 1872, the Companies Act, 2013, and any other applicable national or international legislation.',
          '“Agreement” — These Terms of Use, the Privacy Policy, the Acceptable Use Policy, and any Order Form, addendum, or supplemental terms, all of which are incorporated herein by reference.',
          '“Content” — Any material in any form — including 3D models, spatial environments, images, video, audio, text, data, designs, code, or any combination thereof — created, uploaded, shared, or transmitted by Us or by Users through the Platform.',
          '“User-Generated Content (UGC)” — Any Content created, uploaded, or submitted by a User, including Inputs, prompts, files, and creative assets.',
          '“AI-Generated Outputs” — Any Content produced by artificial intelligence or generative models within the Platform in response to User Inputs.',
          '“Inputs” — All data, prompts, files, images, audio, video, text, URLs, or other information submitted by You to the Platform or its AI features.',
          '“Intellectual Property” — All patents, trademarks, service marks, trade names, domain names, copyrights, database rights, designs, trade secrets, algorithms, source code, software, know-how, and any other intellectual property rights, whether registered or unregistered, owned or licensed by Ctruh.',
          '“Confidential Information” — Any information relating to the business, technology, financials, users, or operations of Ctruh that is not publicly available, including this Agreement, the Platform’s source code, algorithms, business models, and any information disclosed under conditions of confidence.',
          '“Platform” — The Commverse Studio web application, desktop application, mobile application, APIs, SDKs, and all associated tools and features, as updated from time to time, accessible at commverse.studio.',
          '“Services” — All tools, features, functionalities, and capabilities made available through the Platform, including 3D creation, spatial design, AI-powered content generation, collaboration tools, and any future additions.',
          '“Registered Account” — A unique account created by a User on the Platform to access the Services.',
          '“Registered User” — A User who has created and maintains a valid Registered Account.',
          '“Subscription Term” — The period during which You have paid for or are otherwise entitled to access the Services under a selected plan.',
          '“Credits” — Units consumed when You generate AI Outputs or use certain features of the Services, as applicable to Your subscription plan.',
          '“Beta Features” — Features released as preview, experimental, or beta, which may be unstable, incomplete, or subject to change or discontinuation without notice.',
          '“Person” — Any natural person, company, corporation, partnership, trust, association, government body, or any other legal entity recognized under Applicable Law.',
          '“You” / “Your” — Any Person, including a Registered User, who accesses, browses, or uses the Platform or Services in any capacity.',
        ],
      },
      {
        type: 'paragraph',
        text: 'Any reference to the singular includes the plural and vice versa. Any reference to a gender includes all genders. Headings are for convenience only and do not affect interpretation. References to a natural person include their heirs and permitted assignees; references to a juristic person include their successors and permitted assignees.',
      },
    ],
  },
  {
    id: '3',
    title: 'Provision of Services',
    subsections: [
      {
        id: '3.1',
        title: 'Purpose and Scope',
        blocks: [
          {
            type: 'paragraph',
            text: 'Commverse Studio is a spatial creation and collaboration platform that enables Users to design, build, share, and interact with 3D environments, immersive experiences, and AI-generated spatial content using tools and capabilities made available on the Platform.',
          },
        ],
      },
      {
        id: '3.2',
        title: 'Account Registration',
        blocks: [
          {
            type: 'paragraph',
            text: 'To access the full range of Services, You must create a Registered Account by providing accurate, complete, and current information. You represent and warrant that:',
          },
          {
            type: 'list',
            items: [
              'All registration information You provide is true, accurate, complete, and up to date;',
              'You will promptly notify Us of any changes to Your registration information;',
              'You will not register on behalf of another person without their express authorization; and',
              'The authenticity of all information and documents provided during registration is Your sole responsibility.',
            ],
          },
          {
            type: 'paragraph',
            text: 'We reserve the right to terminate or suspend any Registered Account that contains false, incomplete, or misleading information, or that appropriates the identity, name, or information of another person or organization.',
          },
        ],
      },
      {
        id: '3.3',
        title: 'Account Security and Responsibility',
        blocks: [
          {
            type: 'paragraph',
            text: 'You are solely responsible for maintaining the confidentiality of Your account credentials (username, password, and API keys). Any access to or use of the Services through Your Registered Account will be deemed to be access or use by You. You agree to:',
          },
          {
            type: 'list',
            items: [
              'Use strong and unique credentials and enable multi-factor authentication where available;',
              'Immediately notify Us at contact@ctruh.com upon discovering any unauthorized access to or use of Your account; and',
              'Accept full responsibility for all activities that occur under Your account.',
            ],
          },
          {
            type: 'paragraph',
            text: 'Ctruh shall not be liable for any loss or damage arising from Your failure to maintain account security.',
          },
        ],
      },
      {
        id: '3.4',
        title: 'Modifications to Services',
        blocks: [
          {
            type: 'paragraph',
            text: 'Subject to Applicable Law, We reserve the right at Our sole discretion and without prior notice to:',
          },
          {
            type: 'list',
            items: [
              'Modify, suspend, limit, or discontinue any part or the whole of the Services, temporarily or permanently;',
              'Introduce, modify, or remove features, tools, or integrations;',
              'Change subscription plans, credit allocations, and pricing; and',
              'Update, patch, or alter the Platform for performance, security, or compliance purposes.',
            ],
          },
          {
            type: 'paragraph',
            text: 'Your continued use of the Services following any such modification constitutes Your deemed acceptance of the Agreement as modified. Where modifications materially affect Your rights, We will provide reasonable advance notice via email or in-Platform notification.',
          },
        ],
      },
      {
        id: '3.5',
        title: 'Technical Support',
        blocks: [
          {
            type: 'paragraph',
            text: 'Ctruh will provide such technical support as it deems necessary for the smooth functioning of the Platform, including regular updates, security patches, bug fixes, and data storage facilities. Support scope varies by subscription plan.',
          },
        ],
      },
      {
        id: '3.6',
        title: 'Communications Consent',
        blocks: [
          {
            type: 'paragraph',
            text: 'By registering on the Platform, You agree and consent to receive all communications — including transactional, operational, and promotional messages — at the email address and mobile number provided, even if such mobile number is registered under the DND/NCPR list under TRAI regulations. You authorize Ctruh to share or disclose such contact information to third-party service providers, affiliates, or authorized agents for the sole purpose of delivering such communications. You may opt out of promotional communications at any time by following the unsubscribe instructions in any such communication.',
          },
        ],
      },
    ],
  },
  {
    id: '4',
    title: 'Pricing, Payments, and Credits',
    subsections: [
      {
        id: '4.1',
        title: 'Subscription Plans',
        blocks: [
          {
            type: 'paragraph',
            text: 'Access to certain Services is subject to payment of applicable fees under a selected subscription plan. Pricing details are published on commverse.studio and may be updated from time to time at Ctruh’s sole discretion. While certain features may currently be available free of charge, We reserve the right to impose charges on any part of the Services in the future. Reasonable prior notice will be provided before any currently free feature becomes a paid feature. If You continue to access such paid features after receiving such notice, all applicable fees shall become due and payable.',
          },
        ],
      },
      {
        id: '4.2',
        title: 'Credit System',
        blocks: [
          {
            type: 'paragraph',
            text: 'Certain features of the Platform operate on a credit-based model. The following terms apply:',
          },
          {
            type: 'list',
            items: [
              'Credits are deducted upon generation of AI Outputs or use of designated credit-consuming features;',
              'Your subscription plan determines Your monthly or total credit allocation;',
              'Credits expire in accordance with Your subscription plan terms;',
              'Unused credits do not roll over to subsequent billing periods unless expressly stated otherwise; and',
              'Ctruh may apply rate limits, throttling, suspension, or termination in cases of abusive, excessive, or automated usage.',
            ],
          },
        ],
      },
      {
        id: '4.3',
        title: 'Payment Terms',
        blocks: [
          {
            type: 'paragraph',
            text: 'All payments for Services are processed through PCI-DSS Level 1 certified third-party payment processors. You agree to:',
          },
          {
            type: 'list',
            items: [
              'Provide accurate, current, and complete billing information;',
              'Maintain valid payment credentials throughout Your Subscription Term;',
              'Authorize Ctruh or its payment processor to charge Your designated payment method for all applicable fees; and',
              'Notify Us immediately upon any change in Your billing information.',
            ],
          },
          {
            type: 'paragraph',
            text: 'All fees are non-refundable except as expressly required by Applicable Law or as separately agreed in writing. If payment fails or is declined, We may immediately suspend or terminate Your access to the Services without prior notice.',
          },
        ],
      },
      {
        id: '4.4',
        title: 'Chargebacks',
        blocks: [
          {
            type: 'paragraph',
            text: 'You agree not to initiate a chargeback or payment reversal with Your bank or payment provider without first contacting Ctruh at legal@ctruh.com and providing Us a reasonable opportunity to resolve the matter. Unauthorized or fraudulent chargebacks may result in immediate suspension or permanent termination of Your account, recovery of outstanding amounts, and such other remedies as are available under Applicable Law.',
          },
        ],
      },
      {
        id: '4.5',
        title: 'Taxes',
        blocks: [
          {
            type: 'paragraph',
            text: 'All fees are exclusive of applicable taxes, levies, duties, and surcharges (including GST, VAT, and withholding tax) unless expressly stated otherwise. You are responsible for paying all such taxes in connection with Your use of the Services.',
          },
        ],
      },
    ],
  },
  {
    id: '5',
    title: 'Permitted Use of Services',
    subsections: [
      {
        id: '5.1',
        title: 'License Grant',
        blocks: [
          {
            type: 'paragraph',
            text: 'Subject to Your compliance with this Agreement, Ctruh grants You a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to access and use the Platform and Services solely for Your lawful internal business or personal purposes during Your Subscription Term. This license does not include any right to:',
          },
          {
            type: 'list',
            items: [
              'Resell, sublicense, or commercially exploit the Services or any part thereof;',
              'Copy, reproduce, or distribute any part of the Platform outside of its intended use;',
              'Create derivative works based on the Platform’s software, algorithms, or underlying technology; or',
              'Use the Services to develop competing products or services.',
            ],
          },
        ],
      },
      {
        id: '5.2',
        title: 'User Obligations',
        blocks: [
          {
            type: 'paragraph',
            text: 'You agree to use the Platform and Services only for purposes permitted by this Agreement and Applicable Law. You further agree to comply with all applicable laws, regulations, and generally accepted industry standards of the jurisdiction from which You access the Services.',
          },
        ],
      },
      {
        id: '5.3',
        title: 'Beta Features',
        blocks: [
          {
            type: 'paragraph',
            text: 'Beta Features are provided “as is” and may be unstable, incomplete, subject to errors, or discontinued at any time without notice. Beta Features are not intended for mission-critical or production-critical use. Ctruh makes no representations or warranties with respect to Beta Features and accepts no liability for any issues arising from their use.',
          },
        ],
      },
    ],
  },
  {
    id: '6',
    title: 'Restrictions on Use',
    blocks: [
      {
        type: 'paragraph',
        text: 'You agree that You will not, and will not permit or facilitate any third party to, directly or indirectly:',
      },
      {
        type: 'list',
        items: [
          'Reverse engineer, decompile, disassemble, or otherwise attempt to derive the source code, algorithms, or underlying structure of the Platform or any part thereof, unless expressly permitted in writing by Ctruh or required by Applicable Law;',
          'Use any robot, spider, crawler, scraper, or other automated device to access, retrieve, index, or mine any portion of the Platform or Services;',
          'Collect, harvest, or aggregate information about other Users in any unlawful manner or for any unauthorized purpose;',
          'Register on the Platform by automated means, under false or fraudulent pretenses, or create multiple accounts for the same individual or organization;',
          'Transmit or upload any viruses, malware, worms, trojan horses, ransomware, spyware, or any other destructive or harmful code through the Platform;',
          'Carry out denial-of-service (DoS), distributed denial-of-service (DDoS), or any other harmful attacks on the Platform or its infrastructure;',
          'Attempt to gain unauthorized access to any part of the Platform, its servers, networks, databases, or connected systems;',
          'Forge headers, manipulate identifiers, or otherwise disguise the origin of any communication or request;',
          'Circumvent, disable, or interfere with any digital rights management, security, or access control mechanisms of the Platform;',
          'Remove, alter, or obscure any proprietary notices, trademarks, or copyright legends appearing on or within the Platform;',
          'Impersonate any person or entity, falsely represent Your affiliation, or misrepresent Your identity or authority;',
          'Use the Platform in any manner that threatens the security, integrity, performance, or availability of the Services;',
          'Insert unauthorized deep links, hyperlinks, or embedded connections to third-party platforms without Ctruh’s prior written consent;',
          'Use the Platform to develop, train, or improve any competing artificial intelligence or machine learning system, product, or service; or',
          'Engage in any activity that is unlawful, harmful, threatening, abusive, defamatory, obscene, or otherwise objectionable under Applicable Law.',
        ],
      },
    ],
  },
  {
    id: '7',
    title: 'Content Standards and User-Generated Content',
    subsections: [
      {
        id: '7.1',
        title: 'Content Responsibility',
        blocks: [
          {
            type: 'paragraph',
            text: 'You are solely and exclusively responsible for all Content You create, upload, publish, share, or transmit through the Platform. You represent and warrant that all such Content:',
          },
          {
            type: 'list',
            items: [
              'Does not infringe, misappropriate, or violate the Intellectual Property rights, privacy rights, or any other rights of any third party;',
              'Does not contain any defamatory, obscene, pornographic, violent, threatening, or discriminatory material;',
              'Does not promote or facilitate illegal activities, harmful substances, or exploitation of minors in any form;',
              'Does not constitute unauthorized advertising, spam, or unsolicited commercial communications; and',
              'Complies with all Applicable Laws and this Agreement.',
            ],
          },
        ],
      },
      {
        id: '7.2',
        title: 'AI Inputs and Outputs',
        blocks: [
          {
            type: 'paragraph',
            text: 'When using AI-powered features of the Platform:',
          },
          {
            type: 'list',
            items: [
              'You are solely responsible for ensuring You hold all necessary rights, licenses, consents, and permissions to submit Inputs, including the right to use any personal data, images, likenesses, brand assets, or third-party content included in Your Inputs;',
              'AI-Generated Outputs are produced by automated systems and may be inaccurate, incomplete, biased, or otherwise unsuitable. Ctruh makes no representations or warranties regarding the accuracy, legality, or fitness for purpose of any Output;',
              'You are solely responsible for reviewing, validating, and determining the appropriateness of all Outputs before any use or publication; and',
              'You agree not to use Inputs or Outputs to generate content that is deceptive, defamatory, infringing, or that violates the rights of any third party.',
            ],
          },
        ],
      },
      {
        id: '7.3',
        title: 'Content Moderation',
        blocks: [
          {
            type: 'paragraph',
            text: 'Ctruh reserves the right (but assumes no obligation) to review, monitor, remove, or disable any Content that, in Our reasonable judgment, violates this Agreement, is harmful, unlawful, or objectionable, or that We are required to remove by Applicable Law or a valid legal order. We will not be liable for any such removal or failure to remove.',
          },
        ],
      },
      {
        id: '7.4',
        title: 'Public and Shared Content',
        blocks: [
          {
            type: 'paragraph',
            text: 'Certain features of the Platform, including shared links or public workspaces, may make Your Content accessible to anyone with the link or to the general public. Such sharing is intentional and controlled by You. You acknowledge that content shared publicly should not include confidential, sensitive, or proprietary information. Ctruh accepts no liability for the use or distribution of Content You choose to share publicly.',
          },
        ],
      },
    ],
  },
  {
    id: '8',
    title: 'Intellectual Property Rights and Data Ownership',
    subsections: [
      {
        id: '8.1',
        title: 'Ctruh Intellectual Property',
        blocks: [
          {
            type: 'paragraph',
            text: 'The Company exclusively owns and reserves all right, title, and interest in and to: the Platform; all Services and their underlying software, code, algorithms, workflows, databases, and architectures; all Intellectual Property created by or for Ctruh; and all data derived from the aggregated or anonymized use of the Services. Subject to Applicable Law, ownership of all Intellectual Property developed in relation to the Platform vests ab initio in Ctruh. No rights are transferred to You except as expressly provided in this Agreement.',
          },
        ],
      },
      {
        id: '8.2',
        title: 'Your Content Ownership',
        blocks: [
          {
            type: 'paragraph',
            text: 'You retain ownership of Your Inputs and User-Generated Content. By submitting Content to the Platform, You grant Ctruh a worldwide, royalty-free, non-exclusive, sublicensable license to host, store, process, reproduce, display, and use Your Content solely to the extent necessary to provide, maintain, improve, and secure the Services. This license terminates upon deletion of Your Content or account, subject to backup and legal retention requirements.',
          },
        ],
      },
      {
        id: '8.3',
        title: 'AI-Generated Outputs Ownership',
        blocks: [
          {
            type: 'paragraph',
            text: 'Subject to successful credit deduction and Your compliance with this Agreement, AI-Generated Outputs produced by the Platform in response to Your Inputs are assigned to You. You acknowledge that Outputs are AI-generated and may be similar or identical to Outputs generated for other Users. Ctruh does not guarantee that Outputs are free from third-party intellectual property claims. You are solely responsible for determining the suitability and legal compliance of Outputs prior to use.',
          },
        ],
      },
      {
        id: '8.4',
        title: 'No Training on Your Data',
        blocks: [
          {
            type: 'paragraph',
            text: 'Ctruh does not use Your Inputs, Outputs, or workspace data to train, fine-tune, or improve shared or foundational AI models without Your explicit, opt-in consent. Inputs and Outputs may be processed transiently for content generation, abuse prevention, security monitoring, and system performance, but not for model training.',
          },
        ],
      },
      {
        id: '8.5',
        title: 'Third-Party Intellectual Property',
        blocks: [
          {
            type: 'paragraph',
            text: 'All third parties owning intellectual property rights have the right to take appropriate action against You for any violation, infringement, or passing off. Ctruh respects all third-party intellectual property rights and accepts no responsibility or liability for any intellectual property infringement committed by You.',
          },
        ],
      },
      {
        id: '8.6',
        title: 'Copyright Infringement and DMCA-Style Procedure',
        blocks: [
          {
            type: 'paragraph',
            text: 'Ctruh adopts a copyright dispute procedure for global interoperability. If You believe that Content on the Platform infringes Your intellectual property rights, please submit a written notice to legal@ctruh.com containing: (a) identification of the protected work; (b) identification of the allegedly infringing material; (c) Your contact information; (d) a good-faith statement; and (e) a statement of accuracy under penalty of perjury. Ctruh will respond to valid notices in accordance with Applicable Law.',
          },
        ],
      },
    ],
  },
  {
    id: '9',
    title: 'Confidentiality',
    blocks: [
      {
        type: 'paragraph',
        text: 'You may, in the course of using the Platform, have access to Confidential Information of Ctruh or confidential information of other Registered Users. You agree to:',
      },
      {
        type: 'list',
        items: [
          'Use Confidential Information solely for the purposes of this Agreement and not for any independent corporate or commercial purpose;',
          'Not disclose Confidential Information to any third party without the prior written consent of the information owner; and',
          'Use at least the same degree of care to protect Confidential Information as You use to protect Your own confidential information, but in no case less than reasonable care.',
        ],
      },
      {
        type: 'paragraph',
        text: 'Confidentiality obligations do not apply to information that: (a) is or becomes publicly available through no fault of Yours; (b) was already known to You prior to disclosure; (c) is lawfully received from a third party without confidentiality restrictions; (d) is independently developed by You without reference to the Confidential Information; or (e) is required to be disclosed by Applicable Law or valid legal process, provided You give Ctruh prompt written notice and cooperate to seek a protective order.',
      },
    ],
  },
  {
    id: '10',
    title: 'Suspension and Termination',
    subsections: [
      {
        id: '10.1',
        title: 'Suspension by Ctruh',
        blocks: [
          {
            type: 'paragraph',
            text: 'We may immediately suspend Your access to the Services, with or without notice (except as required by Applicable Law), if We determine that:',
          },
          {
            type: 'list',
            items: [
              'You have materially breached any provision of this Agreement or Applicable Law;',
              'There is an unusual or suspicious spike in Your usage of the Services or evidence of fraudulent activity;',
              'Your use of the Services threatens the security, integrity, or availability of the Platform;',
              'Provision of the Services to You has become prohibited by Applicable Law or regulatory order; or',
              'Information in Your account is untrue, inaccurate, incomplete, or misleading.',
            ],
          },
          {
            type: 'paragraph',
            text: 'Ctruh shall have no liability for any loss, damage, or consequences arising from any such suspension.',
          },
        ],
      },
      {
        id: '10.2',
        title: 'Termination by Ctruh',
        blocks: [
          {
            type: 'paragraph',
            text: 'We reserve the right to terminate Your access to the Services or any part thereof, at any time, with or without notice, if:',
          },
          {
            type: 'list',
            items: [
              'You cause, directly or indirectly, a breach of any part of this Agreement;',
              'A third-party service provider essential to the Services terminates its relationship with Us;',
              'Provision of the Services is no longer commercially viable or feasible;',
              'You are a repeat infringer of this Agreement or Applicable Law; or',
              'Termination is required by Applicable Law, government order, or a court of competent jurisdiction.',
            ],
          },
        ],
      },
      {
        id: '10.3',
        title: 'Termination by You',
        blocks: [
          {
            type: 'paragraph',
            text: 'You may terminate this Agreement by ceasing all use of the Services and deleting Your Registered Account, with 30 days’ prior written notice to contact@ctruh.com. Termination does not entitle You to a refund of any prepaid fees except as required by Applicable Law.',
          },
        ],
      },
      {
        id: '10.4',
        title: 'Effect of Termination',
        blocks: [
          {
            type: 'paragraph',
            text: 'Upon termination of this Agreement for any reason: (a) Your license to access and use the Services is immediately revoked; (b) Ctruh will delete or anonymize Your personal data in accordance with the Privacy Policy; (c) provisions of this Agreement that by their nature should survive termination — including Sections on Intellectual Property, Confidentiality, Limitation of Liability, Indemnification, Governing Law, and Definitions — shall continue in full force and effect.',
          },
        ],
      },
    ],
  },
  {
    id: '11',
    title: 'Non-Compete and Non-Solicitation',
    blocks: [
      {
        type: 'paragraph',
        text: 'During the term of this Agreement and for a period of one (1) year following its termination, You agree that You will not, directly or indirectly:',
      },
      {
        type: 'list',
        items: [
          'Solicit, recruit, or encourage any employee, consultant, contractor, user, or partner of Ctruh to terminate or diminish their relationship with Ctruh or to engage with You or any third party in a competing capacity;',
          'Develop, offer, or operate any product, platform, or service that is substantially similar to or directly competitive with Commverse Studio or the Services, using knowledge or information derived from Your access to the Platform or Confidential Information of Ctruh; or',
          'Use any Confidential Information of Ctruh for the benefit of any competing business.',
        ],
      },
    ],
  },
  {
    id: '12',
    title: 'Representations and Warranties',
    subsections: [
      {
        id: '12.1',
        title: 'Your Representations',
        blocks: [
          {
            type: 'paragraph',
            text: 'You represent and warrant that:',
          },
          {
            type: 'list',
            items: [
              'You are lawfully existing under Applicable Laws and have full power and authority to enter into and perform this Agreement;',
              'You have all necessary authorizations required to perform Your obligations hereunder;',
              'This Agreement constitutes a legal, valid, and binding obligation on You, enforceable in accordance with its terms;',
              'Your execution and performance of this Agreement will not violate any provision of applicable law, conflict with any agreement to which You are a party, or violate any court order or regulatory requirement;',
              'You have not been induced to enter this Agreement by any representation not expressly set forth herein; and',
              'You hold all necessary rights, licenses, consents, and permissions for all Content and Inputs You submit to the Platform.',
            ],
          },
        ],
      },
      {
        id: '12.2',
        title: 'Disclaimer of Warranties',
        blocks: [
          {
            type: 'paragraph',
            text: 'TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, CTRUH EXPRESSLY DISCLAIMS ALL WARRANTIES, EXPRESS, IMPLIED, OR STATUTORY, IN RESPECT OF THE PLATFORM AND SERVICES, INCLUDING BUT NOT LIMITED TO:',
            uppercase: true,
          },
          {
            type: 'list',
            items: [
              'That the Services will be uninterrupted, error-free, secure, or available at all times;',
              'That defects, bugs, or errors will be corrected;',
              'That the Platform will be compatible with all devices, operating systems, browsers, or networks;',
              'The accuracy, reliability, or completeness of any data, Output, or information provided through the Services;',
              'The security of Your data against unauthorized access, disclosure, or loss;',
              'That AI-Generated Outputs will be accurate, non-infringing, unbiased, or suitable for any particular purpose;',
              'That the Services are fit for a particular purpose or meet Your requirements; or',
              'That the Services are accessible from all locations or jurisdictions.',
            ],
          },
          {
            type: 'paragraph',
            text: 'YOUR USE OF THE SERVICES IS ENTIRELY AT YOUR OWN RISK.',
            uppercase: true,
          },
        ],
      },
    ],
  },
  {
    id: '13',
    title: 'Limitation of Liability',
    blocks: [
      {
        type: 'paragraph',
        text: 'TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:',
        uppercase: true,
      },
      {
        type: 'paragraph',
        text: '(a) CTRUH SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, LOSS OF DATA, LOSS OF GOODWILL, BUSINESS INTERRUPTION, OR COST OF SUBSTITUTE SERVICES, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF OR INABILITY TO USE THE SERVICES, REGARDLESS OF THE CAUSE OF ACTION OR THE THEORY OF LIABILITY, AND EVEN IF CTRUH HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.',
        uppercase: true,
      },
      {
        type: 'paragraph',
        text: '(b) CTRUH’S TOTAL CUMULATIVE LIABILITY TO YOU FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THIS AGREEMENT OR THE SERVICES SHALL NOT EXCEED THE GREATER OF: (i) THE TOTAL FEES PAID BY YOU TO CTRUH IN THE THREE (3) MONTHS IMMEDIATELY PRECEDING THE CLAIM, OR (ii) INR 10,000 (TEN THOUSAND INDIAN RUPEES), WHICHEVER IS HIGHER.',
        uppercase: true,
      },
      {
        type: 'paragraph',
        text: '(c) PROVISION OF THE PLATFORM DOES NOT CONSTITUTE AN AGENCY RELATIONSHIP. OUR RELATIONSHIP WITH EACH USER IS ON A PRINCIPAL-TO-PRINCIPAL BASIS ONLY. YOU ARE SOLELY RESPONSIBLE FOR ANY BREACH OF YOUR OBLIGATIONS UNDER THIS AGREEMENT.',
        uppercase: true,
      },
      {
        type: 'paragraph',
        text: 'Some jurisdictions do not allow the exclusion or limitation of certain types of liability. In such jurisdictions, our liability is limited to the greatest extent permitted by Applicable Law.',
      },
    ],
  },
  {
    id: '14',
    title: 'Indemnification',
    blocks: [
      {
        type: 'paragraph',
        text: 'You agree to defend, indemnify, and hold harmless Ctruh, and its officers, directors, employees, consultants, representatives, agents, affiliates, and successors from and against any and all claims, actions, demands, proceedings, losses, liabilities, damages, settlements, penalties, fines, costs, and expenses (including reasonable legal fees) arising out of or relating to:',
      },
      {
        type: 'list',
        items: [
          'Your unauthorized, illegal, or unlawful access to or use of the Services;',
          'Your breach of any provision of this Agreement or Applicable Law;',
          'Your Content, Inputs, or AI-Generated Outputs and any claim that they infringe third-party intellectual property, privacy, or other rights;',
          'Your misuse of any personal data, image, likeness, or third-party asset;',
          'Any marketplace enforcement action, platform takedown, or regulatory action arising from Your use of the Services; and',
          'Any claim by a third party arising from Your use of the Platform.',
        ],
      },
      {
        type: 'paragraph',
        text: 'Ctruh reserves the right to assume exclusive control of any matter subject to indemnification by You, in which case You agree to cooperate with Ctruh in asserting any available defenses.',
      },
    ],
  },
  {
    id: '15',
    title: 'Third-Party Links and Services',
    blocks: [
      {
        type: 'paragraph',
        text: 'The Platform may include or display links to third-party websites, applications, or services not operated or controlled by Ctruh. Such third-party services are governed by their own terms and privacy policies. Ctruh does not endorse, warrant, or accept responsibility for any third-party content, accuracy, products, or services. Any transactions between You and third-party providers are solely between You and that third party. You access third-party services entirely at Your own risk.',
      },
    ],
  },
  {
    id: '16',
    title: 'Governing Law and Dispute Resolution',
    subsections: [
      {
        id: '16.1',
        title: 'Governing Law',
        blocks: [
          {
            type: 'paragraph',
            text: 'This Agreement shall be governed by and construed in accordance with the laws of India, without regard to its conflict of law provisions. All disputes arising out of or in connection with this Agreement shall be subject to the exclusive jurisdiction of the courts located at Bengaluru, Karnataka, India.',
          },
        ],
      },
      {
        id: '16.2',
        title: 'Informal Resolution',
        blocks: [
          {
            type: 'paragraph',
            text: 'Before initiating any legal proceedings, You agree to contact Ctruh at legal@ctruh.com and provide a written description of the dispute and the relief sought. The parties shall negotiate in good faith for a period of thirty (30) days from receipt of such notice before commencing formal proceedings.',
          },
        ],
      },
      {
        id: '16.3',
        title: 'Limitation Period',
        blocks: [
          {
            type: 'paragraph',
            text: 'Any claim or cause of action arising out of or related to Your use of the Services or this Agreement must be commenced within one (1) year after the claim or cause of action arises. Claims not filed within this period are permanently barred.',
          },
        ],
      },
      {
        id: '16.4',
        title: 'Class Action Waiver',
        blocks: [
          {
            type: 'paragraph',
            text: 'All claims between the parties related to this Agreement will be litigated individually. The parties will not consolidate or seek class treatment for any claim unless previously agreed to in writing by Ctruh.',
          },
        ],
      },
    ],
  },
  {
    id: '17',
    title: 'Disclaimers',
    blocks: [
      {
        type: 'paragraph',
        text: 'The information, software, Content, and Services forming part of the Platform may contain inaccuracies or typographical errors contributed by various users. Any advice, guidance, or information received or inferred through the Services should not be relied upon for personal, legal, financial, medical, or professional decisions. Users should consult an appropriate qualified professional for advice specific to their situation.',
      },
      {
        type: 'paragraph',
        text: 'Ctruh does not accept responsibility for any viruses, malware, or other harmful content transmitted by third parties through the Platform.',
      },
      {
        type: 'paragraph',
        text: 'EXCEPT AS EXPRESSLY PROVIDED IN THIS AGREEMENT AND TO THE EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICES ARE PROVIDED “AS IS” AND “AS AVAILABLE.” CTRUH MAKES NO WARRANTIES OF ANY KIND, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, ACCURACY, OR UNINTERRUPTED AVAILABILITY.',
        uppercase: true,
      },
    ],
  },
  {
    id: '18',
    title: 'Force Majeure',
    blocks: [
      {
        type: 'paragraph',
        text: 'Ctruh shall not be liable for any delay, failure, or interruption of the Services resulting from causes beyond Our reasonable control, including but not limited to acts of God, natural disasters, epidemics, pandemics, war, terrorism, riots, governmental embargoes, acts of civil or military authorities, fire, floods, accidents, power failures, network infrastructure failures, cyberattacks, strikes, or shortages of transportation, fuel, energy, labor, or materials. In such events, Ctruh will use commercially reasonable efforts to resume Services as soon as practicable.',
      },
    ],
  },
  {
    id: '19',
    title: 'Export Controls and Sanctions Compliance',
    blocks: [
      {
        type: 'paragraph',
        text: 'The Platform and Services may be subject to applicable export control laws and economic sanctions regulations. You represent and warrant that You are not located in, under the control of, or a national or resident of any country subject to applicable trade embargoes or sanctions, and that You are not listed on any government-maintained list of prohibited or restricted parties. You agree to comply with all applicable export control and sanctions laws in connection with Your use of the Services.',
      },
    ],
  },
  {
    id: '20',
    title: 'Miscellaneous',
    subsections: [
      {
        id: '20.1',
        title: 'Entire Agreement',
        blocks: [
          {
            type: 'paragraph',
            text: 'This Agreement, together with the Privacy Policy, Acceptable Use Policy, and any applicable Order Form, constitutes the entire agreement between You and Ctruh with respect to the subject matter hereof and supersedes all prior and contemporaneous understandings, agreements, representations, and warranties.',
          },
        ],
      },
      {
        id: '20.2',
        title: 'Severability',
        blocks: [
          {
            type: 'paragraph',
            text: 'If any provision of this Agreement is found to be invalid, unlawful, or unenforceable by a court of competent jurisdiction, that provision shall be modified to the minimum extent necessary to make it enforceable, and the remaining provisions shall continue in full force and effect. Prior acts of either party taken under an unenforceable provision shall remain valid and binding.',
          },
        ],
      },
      {
        id: '20.3',
        title: 'Waiver',
        blocks: [
          {
            type: 'paragraph',
            text: 'No waiver by Ctruh of any breach or default of any provision of this Agreement shall constitute a waiver of any subsequent breach or default, or a waiver of the underlying provision itself. Failure or delay by Ctruh to exercise any right under this Agreement shall not act as a waiver of that right.',
          },
        ],
      },
      {
        id: '20.4',
        title: 'Assignment',
        blocks: [
          {
            type: 'paragraph',
            text: 'You shall not assign, transfer, delegate, or otherwise dispose of any of Your rights or obligations under this Agreement without the prior written consent of Ctruh. Ctruh may freely assign, transfer, or delegate any of its rights and obligations under this Agreement, in whole or in part, to any affiliate, successor entity, or as part of a corporate restructuring, merger, or acquisition. You acknowledge that Ctruh may deliver Services through affiliates or authorized third parties.',
          },
        ],
      },
      {
        id: '20.5',
        title: 'Notices',
        blocks: [
          {
            type: 'paragraph',
            text: 'All notices under this Agreement shall be in writing. Ctruh may post notices within the Platform or send notices to Your registered email address. You will be deemed to have received electronic notices 24 hours after transmission. Notices to Ctruh must be sent to legal@ctruh.com. For formal legal notices, a copy must be sent to the Registered Address.',
          },
        ],
      },
      {
        id: '20.6',
        title: 'Display of Association',
        blocks: [
          {
            type: 'paragraph',
            text: 'Ctruh reserves the right to display and publicize its association with Registered Users and the Services provided to them in Ctruh’s marketing, promotional materials, and branding collateral, unless You notify Us in writing that You object to such use.',
          },
        ],
      },
      {
        id: '20.7',
        title: 'No Agency',
        blocks: [
          {
            type: 'paragraph',
            text: 'Nothing in this Agreement shall be construed to create any agency, partnership, joint venture, employment, or franchise relationship between You and Ctruh. You have no authority to bind Ctruh in any manner whatsoever.',
          },
        ],
      },
      {
        id: '20.8',
        title: 'Electronic Records',
        blocks: [
          {
            type: 'paragraph',
            text: 'This Agreement is an electronic record generated by a computer system and does not require any physical or digital signatures. It is governed by the provisions of the Information Technology Act, 2000 and applicable rules thereunder.',
          },
        ],
      },
      {
        id: '20.9',
        title: 'Updates to Terms',
        blocks: [
          {
            type: 'paragraph',
            text: 'Ctruh reserves the right to modify these Terms at any time. Material changes will be communicated via in-Platform notification or email to Your registered address, with reasonable advance notice. Continued use of the Services after the effective date of any modification constitutes Your acceptance of the updated Terms.',
          },
        ],
      },
    ],
  },
  {
    id: '21',
    title: 'Contact Information',
    blocks: [
      {
        type: 'paragraph',
        text: 'For any questions, concerns, or notices relating to this Agreement, please contact:',
      },
    ],
  },
];

export const termsContactInfo: TermsInfoItem[] = [
  {
    label: 'General Support',
    value: 'contact@ctruh.com',
    href: 'mailto:contact@ctruh.com',
  },
  {
    label: 'Legal & Compliance',
    value: 'legal@ctruh.com',
    href: 'mailto:legal@ctruh.com',
  },
  {
    label: 'Privacy / DPO',
    value: 'privacy@ctruh.com',
    href: 'mailto:privacy@ctruh.com',
  },
  {
    label: 'Website',
    value: 'www.ctruh.com',
    href: 'https://www.ctruh.com',
  },
  {
    label: 'Platform',
    value: 'commverse.studio',
    href: 'https://commverse.studio',
  },
];

export const termsClosingNotes = [
  'This document constitutes the complete Terms of Use of Commverse Studio by Ctruh Technologies Pvt. Ltd. All prior versions are hereby superseded.',
  '© 2026 Ctruh Technologies Pvt. Ltd. All Rights Reserved.',
];
