// import type { ICategoryL1 } from '../types';
import {} from // bath_and_body,
// bronzers_and_contours,
// cheeks_and_glow,
// cleansing_and_exfoliation,
// concealers_and_correctors,
// eye_value_set,
// eyebrows,
// eyeliners,
// eyeshadow,
// face_makeup,
// face_mask,
// finish_types,
// for_you,
// foundations_by_finish,
// foundations_by_skin_type,
// gifting,
// hair_care,
// kohl_and_kajal,
// lip_care,
// lip_enhancers_and_other,
// lipstick_forms,
// lipstick_sets_and_combos,
// long_lasting_lipsticks,
// mascaras,
// moisturizers,
// natures_blend,
// new_new,
// primers_and_removers,
// setting_and_finishing,
// sugar_play,
// sugar_pop,
// traditional_and_essentials,
'./Navbar';

// export const CATEGORIES_DATA: Omit<ICategoryL1, 'component' | 'path' | 'id'>[] = [
//   {
//     level: 1,
//     label: 'For You',
//     category: 'for_you',
//     subCategories: [new_new, sugar_play], // only new is reserved keyword we can't use new
//   },
//   {
//     level: 1,
//     label: 'Lips',
//     category: 'lips',
//     subCategories: [
//       finish_types,
//       lipstick_forms,
//       long_lasting_lipsticks,
//       lip_care,
//       lip_enhancers_and_other,
//       lipstick_sets_and_combos,
//     ],
//   },
//   {
//     level: 1,
//     label: 'Eyes',
//     category: 'eyes',
//     subCategories: [kohl_and_kajal, mascaras, eyeliners, eyeshadow, eyebrows, eye_value_set],
//   },
//   {
//     level: 1,
//     label: 'Face',
//     category: 'face',
//     subCategories: [
//       face_makeup,
//       traditional_and_essentials,
//       cheeks_and_glow,
//       setting_and_finishing,
//       primers_and_removers,
//       bronzers_and_contours,
//       concealers_and_correctors,
//       foundations_by_skin_type,
//       foundations_by_finish,
//     ],
//   },
//   {
//     level: 1,
//     label: 'Skin',
//     category: 'skin',
//     subCategories: [moisturizers, cleansing_and_exfoliation, natures_blend, face_mask],
//   },
//   {
//     level: 1,
//     label: 'Collections',
//     category: 'collections',
//     subCategories: [bath_and_body, sugar_pop, hair_care, gifting],
//   },
// ];
